apiVersion: apps/v1
kind: Deployment
metadata:
  name: benchmark-stateful-functions
spec:
  replicas: 2
  selector:
      matchLabels:
        app: benchmark-stateful-functions
  template:
    metadata:
      labels:
        app: benchmark-stateful-functions
    spec:
      containers:
        - name: main
          image: eu.gcr.io/martijns/benchmark-statefun-functions
          imagePullPolicy: Always
          # imagePullPolicy: Never
          resources:
            requests:
              cpu: 2
          ports:
            - containerPort: 1108
