# From https://nightlies.apache.org/flink/flink-statefun-docs-release-3.0/docs/deployment/overview/
apiVersion: v1
kind: Service
metadata:
  name: statefun-jobmanager-rest
spec:
  type: NodePort
  ports:
    - name: rest
      port: 8081
      targetPort: 8081
      nodePort: 30081
  selector:
    app: statefun
    component: jobmanager