name: cloudburst
channels:
  - conda-forge
  - defaults
dependencies:
  - abseil-cpp=20210324.2
  - arrow-cpp=5.0.0
  - aws-c-cal=0.5.11
  - aws-c-common=0.6.2
  - aws-c-event-stream=0.2.7
  - aws-c-io=0.10.5
  - aws-checksums=0.1.11
  - aws-sdk-cpp=1.8.186
  - bzip2=1.0.8
  - c-ares=1.17.2
  - ca-certificates=2021.5.30
  - certifi=2021.5.30
  - gflags=2.2.2
  - glog=0.5.0
  - grpc-cpp=1.40.0
  - krb5=1.19.2
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libcurl=7.79.1
  - libcxx=12.0.0
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.10
  - libffi=3.3
  - libgfortran=5.0.0
  - libgfortran5=9.3.0
  - liblapack=3.9.0
  - libnghttp2=1.43.0
  - libopenblas=0.3.17
  - libprotobuf=3.18.0
  - libssh2=1.10.0
  - libthrift=0.15.0
  - libutf8proc=2.6.1
  - llvm-openmp=12.0.1
  - lz4-c=1.9.3
  - ncurses=6.2
  - openssl=1.1.1l
  - orc=1.7.0
  - parquet-cpp=1.5.1
  - pip=21.0.1
  - pyarrow=5.0.0
  - python=3.7.11
  - python_abi=3.7
  - re2=2021.09.01
  - readline=8.1
  - snappy=1.1.8
  - sqlite=3.36.0
  - tk=8.6.11
  - wheel=0.37.0
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.5.0
  - pip:
    - charset-normalizer==2.0.6
    - click==8.0.1
    - cloudpickle==0.6.1
    - coverage==4.5.4
    - entrypoints==0.3
    - flake8==3.7.7
    - flask==2.0.1
    - idna==3.2
    - importlib-metadata==4.8.1
    - itsdangerous==2.0.1
    - jinja2==3.0.1
    - markupsafe==2.0.1
    - mccabe==0.6.1
    - numpy==1.16.6
    - pandas==0.25.1
    - protobuf==3.18.0
    - pycodestyle==2.5.0
    - pyflakes==2.1.1
    - python-dateutil==2.8.2
    - pytz==2021.3
    - pyyaml==5.1.2
    - pyzmq==17.1.2
    - requests==2.26.0
    - setuptools==45.2.0
    - six==1.16.0
    - typing-extensions==3.10.0.2
    - urllib3==1.26.7
    - werkzeug==2.0.1
    - zipp==3.6.0
    - zmq==0.0.0
