apiVersion: cloudstate.io/v1alpha1
kind: StatefulStore
metadata:
  name: order-store
spec:
  type: InMemory
---
apiVersion: cloudstate.io/v1alpha1
kind: StatefulService
metadata:
  name: order-service
  labels:
    app: order-service
spec:
  datastore:
    name: order-store
  containers:
    - image: benchmark-cloudstate-order-service
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: default
spec:
  ports:
  - name: grpc
    port: 80
    protocol: TCP
    targetPort: 8013
  sessionAffinity: None
  type: ClusterIP
  selector:
    cloudstate.io/statefulService: order-service
