apiVersion: apps/v1
kind: Deployment
metadata:
  name: benchmark-api
  namespace: benchmark
spec:
  replicas: 2
  selector:
    matchLabels:
      app: benchmark-api
  template:
    metadata:
      labels:
        app: benchmark-api
    spec:
      containers:
        - name: main
          image: benchmark-statefun-api
          # imagePullPolicy: Always
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
