name: Orleans

on:
  push:
    branches: [ main ]
    paths:
      - 'orleans/**'
      - '.github/workflows/orleans.yml'

env:
  IMAGE_NAME: benchmark-orleans

jobs:
  build-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GCR
        uses: docker/login-action@v2
        with:
          username: _json_key
          password: "${{ secrets.GC_JSON_KEY }}"
          registry: eu.gcr.io

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          context: orleans
          file: orleans/benchmark.API/Dockerfile
          tags: eu.gcr.io/${{ secrets.GC_PROJECT_ID }}/${{ env.IMAGE_NAME }}
