name: Statefun

on:
  push:
    branches: [ main ]
    paths:
      - 'statefun/**'
      - '.github/workflows/statefun.yml'

env:
  FUNCTIONS_IMAGE_NAME: benchmark-statefun-functions
  API_IMAGE_NAME: benchmark-statefun-api

defaults:
  run:
    working-directory: statefun

jobs:
  build-push-stateful-functions-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Java 11
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 11

      - name: Validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Execute Gradle build
        run: ./gradlew :stateful-functions:build

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GCR
        uses: docker/login-action@v2
        with:
          username: _json_key
          password: "${{ secrets.GC_JSON_KEY }}"
          registry: eu.gcr.io

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          context: statefun
          file: statefun/stateful-functions/Dockerfile
          tags: eu.gcr.io/${{ secrets.GC_PROJECT_ID }}/${{ env.FUNCTIONS_IMAGE_NAME }}
          
  build-push-api-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Java 11
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 11

      - name: Validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Execute Gradle build
        run: ./gradlew :api:build

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GCR
        uses: docker/login-action@v2
        with:
          username: _json_key
          password: "${{ secrets.GC_JSON_KEY }}"
          registry: eu.gcr.io

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          context: statefun
          file: statefun/api/Dockerfile
          tags: eu.gcr.io/${{ secrets.GC_PROJECT_ID }}/${{ env.API_IMAGE_NAME }}
